import { config } from "dotenv";
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { pathToFileURL } from "node:url";

import { getDB } from "../../server/utils/db";
import * as schema from "../../server/database/schema";

/**
 * Task 6 (migration), Step 4 — Creem reconciliation.
 *
 * Answers one question with a machine-readable verdict: **does every billing
 * fact the legacy stack holds exist, unchanged, in Convex?** It compares the
 * legacy Neon state (`creem_subscription`, `events`) with the Convex deployment
 * (`internal.billing.reconcileSnapshot`) on the natural keys — Creem's own
 * subscription/customer/order ids and the legacy row ids — never on internal
 * `_id`s, which are generated by the component at import time.
 *
 * Direction: the legacy side is the reference. A fact that exists only in Convex
 * is *not* a failure — after the cutover the new stack keeps selling — so those
 * are reported under `notes`, while a fact that is missing from Convex or that
 * disagrees with its legacy twin is a `mismatch` and exits `1`.
 *
 * Output contains identifiers and statuses only: no email, no name, no address.
 *
 * Usage:
 *   npx tsx scripts/migration/reconcile-creem.ts                    # dev
 *   NUXT_ENV=prod npx tsx scripts/migration/reconcile-creem.ts      # .env.prod
 *   npx tsx scripts/migration/reconcile-creem.ts --convex-json .gate/convex-billing.json
 *   npx tsx scripts/migration/reconcile-creem.ts --out .gate/creem-reconcile.json
 *
 * Read-only on both sides: the only write is the `--out` report.
 */

const PERIOD_TOLERANCE_MS = 1000;

export interface LegacySubscription {
    /** Creem's subscription id; `null` while the row is still pending. */
    creemSubscriptionId: string | null;
    /** Legacy organization the subscription belongs to. */
    referenceId: string;
    productId: string;
    status: string;
    creemCustomerId: string | null;
    creemOrderId: string | null;
    periodEnd: string | null;
    cancelAtPeriodEnd: boolean;
}

export interface LegacyEvent {
    legacyId: string;
    organizationLegacyId: string;
    tier: string;
    creemOrderId: string | null;
    creemCheckoutId: string | null;
}

export interface LegacyBillingState {
    subscriptions: LegacySubscription[];
    events: LegacyEvent[];
}

export interface ConvexSubscription {
    id: string;
    organizationId: string;
    legacyId: string | null;
    customerId: string;
    productId: string;
    status: string;
    currentPeriodEnd: string | null;
    cancelAtPeriodEnd: boolean;
}

export interface ConvexEvent {
    id: string;
    legacyId: string | null;
    organizationId: string;
    tier: string;
    creemOrderId: string | null;
    creemCheckoutId: string | null;
    unlockedAt: number | null;
}

export interface ConvexBillingState {
    configured: Array<{ tier: string; productId: string }>;
    organizations: Array<{ id: string; legacyId: string | null; customerId: string | null }>;
    subscriptions: ConvexSubscription[];
    events: ConvexEvent[];
}

export interface Mismatch {
    kind: string;
    subject: string;
    detail?: Record<string, unknown>;
}

export interface ReconciliationReport {
    mismatches: Mismatch[];
    notes: Mismatch[];
    counts: {
        legacySubscriptions: number;
        convexSubscriptions: number;
        legacyEvents: number;
        convexEvents: number;
        organizationsMapped: number;
    };
}

const instant = (value: string | null | undefined): number | null => {
    if (!value) return null;
    const parsed = Date.parse(value);
    return Number.isNaN(parsed) ? null : parsed;
};

/**
 * Compares the two states. Pure: no I/O, no clock, no environment — which is what
 * makes the rules below testable without a database or a deployment.
 */
export function compareBillingStates(
    legacy: LegacyBillingState,
    convex: ConvexBillingState,
): ReconciliationReport {
    const mismatches: Mismatch[] = [];
    const notes: Mismatch[] = [];

    // ---------------------------------------------------------------------
    // Organizations: a legacy tenant with no Convex twin means every billing
    // fact under it is unreachable, so it is checked before anything else.
    // ---------------------------------------------------------------------
    const orgByLegacyId = new Map<string, string>();
    for (const organization of convex.organizations) {
        if (organization.legacyId) orgByLegacyId.set(organization.legacyId, organization.id);
    }

    const legacyOrgIds = new Set<string>([
        ...legacy.subscriptions.map((subscription) => subscription.referenceId),
        ...legacy.events.map((event) => event.organizationLegacyId),
    ]);

    for (const legacyOrgId of legacyOrgIds) {
        if (!orgByLegacyId.has(legacyOrgId)) {
            mismatches.push({
                kind: "organization_unmapped",
                subject: legacyOrgId,
                detail: { reason: "no Convex organization carries this legacyId" },
            });
        }
    }

    // ---------------------------------------------------------------------
    // Subscriptions: matched on Creem's subscription id.
    // ---------------------------------------------------------------------
    const subscriptionById = new Map(convex.subscriptions.map((item) => [item.id, item]));
    const legacySubscriptionIds = new Set<string>();

    for (const legacySubscription of legacy.subscriptions) {
        const subject = legacySubscription.creemSubscriptionId ?? `pending:${legacySubscription.referenceId}`;

        if (!legacySubscription.creemSubscriptionId) {
            // The legacy plugin writes the row before Creem returns the id; a row
            // still without one never completed, but it must still be accounted
            // for rather than silently dropped.
            mismatches.push({
                kind: "subscription_missing_in_convex",
                subject,
                detail: { status: legacySubscription.status, productId: legacySubscription.productId },
            });
            continue;
        }

        legacySubscriptionIds.add(legacySubscription.creemSubscriptionId);
        const twin = subscriptionById.get(legacySubscription.creemSubscriptionId);

        if (!twin) {
            mismatches.push({
                kind: "subscription_missing_in_convex",
                subject,
                detail: { status: legacySubscription.status, productId: legacySubscription.productId },
            });
            continue;
        }

        if (twin.status !== legacySubscription.status) {
            mismatches.push({
                kind: "subscription_status_mismatch",
                subject,
                detail: { legacy: legacySubscription.status, convex: twin.status },
            });
        }

        if (twin.productId !== legacySubscription.productId) {
            mismatches.push({
                kind: "subscription_product_mismatch",
                subject,
                detail: { legacy: legacySubscription.productId, convex: twin.productId },
            });
        }

        if (twin.cancelAtPeriodEnd !== legacySubscription.cancelAtPeriodEnd) {
            mismatches.push({
                kind: "subscription_cancel_at_period_end_mismatch",
                subject,
                detail: { legacy: legacySubscription.cancelAtPeriodEnd, convex: twin.cancelAtPeriodEnd },
            });
        }

        if (
            legacySubscription.creemCustomerId &&
            twin.customerId !== legacySubscription.creemCustomerId
        ) {
            mismatches.push({
                kind: "subscription_customer_mismatch",
                subject,
                detail: { legacy: legacySubscription.creemCustomerId, convex: twin.customerId },
            });
        }

        const legacyPeriodEnd = instant(legacySubscription.periodEnd);
        const convexPeriodEnd = instant(twin.currentPeriodEnd);
        if (legacyPeriodEnd !== null || convexPeriodEnd !== null) {
            const sameInstant =
                legacyPeriodEnd !== null &&
                convexPeriodEnd !== null &&
                Math.abs(legacyPeriodEnd - convexPeriodEnd) <= PERIOD_TOLERANCE_MS;
            if (!sameInstant) {
                mismatches.push({
                    kind: "subscription_period_end_mismatch",
                    subject,
                    detail: {
                        legacy: legacySubscription.periodEnd,
                        convex: twin.currentPeriodEnd,
                    },
                });
            }
        }

        // The billing entity is what makes a charge org-scoped: a subscription
        // filed under the wrong organization is a cross-tenant leak, not a typo.
        const expectedOrgId = orgByLegacyId.get(legacySubscription.referenceId);
        if (expectedOrgId && twin.organizationId !== expectedOrgId) {
            mismatches.push({
                kind: "subscription_entity_mismatch",
                subject,
                detail: {
                    legacyOrganizationId: legacySubscription.referenceId,
                    convexOrganizationId: twin.organizationId,
                },
            });
        }
    }

    for (const convexSubscription of convex.subscriptions) {
        if (!legacySubscriptionIds.has(convexSubscription.id)) {
            notes.push({
                kind: "subscription_only_in_convex",
                subject: convexSubscription.id,
                detail: { status: convexSubscription.status, productId: convexSubscription.productId },
            });
        }
    }

    // ---------------------------------------------------------------------
    // Events: matched on the legacy row id, and held to the same predicates the
    // webhook fulfillment uses (`tier`, `creemOrderId`, `creemCheckoutId`) —
    // they are what a refund needs to find its event again.
    // ---------------------------------------------------------------------
    const eventsByLegacyId = new Map<string, ConvexEvent>();
    for (const event of convex.events) {
        if (event.legacyId) eventsByLegacyId.set(event.legacyId, event);
    }

    const legacyEventIds = new Set(legacy.events.map((event) => event.legacyId));

    for (const legacyEvent of legacy.events) {
        const subject = legacyEvent.legacyId;
        const twin = eventsByLegacyId.get(subject);

        if (!twin) {
            // A paid legacy event with no Convex twin is the worst case: the
            // customer paid and the new stack would ask again.
            mismatches.push({
                kind: "event_missing_in_convex",
                subject,
                detail: { tier: legacyEvent.tier, organizationId: legacyEvent.organizationLegacyId },
            });
            continue;
        }

        if (twin.tier !== legacyEvent.tier) {
            mismatches.push({
                kind: "event_tier_mismatch",
                subject,
                detail: { legacy: legacyEvent.tier, convex: twin.tier },
            });
        }

        if ((twin.creemOrderId ?? null) !== (legacyEvent.creemOrderId ?? null)) {
            mismatches.push({
                kind: "event_order_id_mismatch",
                subject,
                detail: { legacy: legacyEvent.creemOrderId, convex: twin.creemOrderId },
            });
        }

        if ((twin.creemCheckoutId ?? null) !== (legacyEvent.creemCheckoutId ?? null)) {
            notes.push({
                kind: "event_checkout_id_differs",
                subject,
                detail: { legacy: legacyEvent.creemCheckoutId, convex: twin.creemCheckoutId },
            });
        }

        const expectedOrgId = orgByLegacyId.get(legacyEvent.organizationLegacyId);
        if (expectedOrgId && twin.organizationId !== expectedOrgId) {
            mismatches.push({
                kind: "event_organization_mismatch",
                subject,
                detail: {
                    legacyOrganizationId: legacyEvent.organizationLegacyId,
                    convexOrganizationId: twin.organizationId,
                },
            });
        }
    }

    for (const event of convex.events) {
        if (!event.legacyId || !legacyEventIds.has(event.legacyId)) {
            notes.push({
                kind: "event_only_in_convex",
                subject: event.id,
                detail: { tier: event.tier, legacyId: event.legacyId },
            });
        }
    }

    return {
        mismatches,
        notes,
        counts: {
            legacySubscriptions: legacy.subscriptions.length,
            convexSubscriptions: convex.subscriptions.length,
            legacyEvents: legacy.events.length,
            convexEvents: convex.events.length,
            organizationsMapped: orgByLegacyId.size,
        },
    };
}

interface CliOptions {
    convexJson: string | null;
    out: string | null;
    prod: boolean;
}

export function parseArgs(argv: string[]): CliOptions {
    const options: CliOptions = { convexJson: null, out: null, prod: false };

    for (let index = 0; index < argv.length; index += 1) {
        const arg = argv[index];

        if (arg === "--convex-json") {
            options.convexJson = argv[++index] ?? null;
        } else if (arg === "--out") {
            options.out = argv[++index] ?? null;
        } else if (arg === "--prod") {
            options.prod = true;
        } else {
            throw new Error(`Unknown argument: ${arg}`);
        }
    }

    return options;
}

async function readLegacyState(): Promise<LegacyBillingState> {
    const db = getDB();

    const [subscriptions, events] = await Promise.all([
        db.select().from(schema.creem_subscription),
        db.select().from(schema.events),
    ]);

    return {
        subscriptions: subscriptions.map((row) => ({
            creemSubscriptionId: row.creemSubscriptionId ?? null,
            referenceId: row.referenceId,
            productId: row.productId,
            status: row.status ?? "pending",
            creemCustomerId: row.creemCustomerId ?? null,
            creemOrderId: row.creemOrderId ?? null,
            periodEnd: row.periodEnd ? row.periodEnd.toISOString() : null,
            cancelAtPeriodEnd: row.cancelAtPeriodEnd ?? false,
        })),
        events: events.map((row) => ({
            legacyId: row.id,
            organizationLegacyId: row.organizationId,
            tier: row.tier,
            creemOrderId: row.creemOrderId ?? null,
            creemCheckoutId: row.creemCheckoutId ?? null,
        })),
    };
}

/**
 * Reads the Convex snapshot through the CLI, which is the documented admin path
 * for `internalQuery`. `--convex-json` exists so the same report can be produced
 * from a captured snapshot (gates, CI, air-gapped review).
 */
function readConvexState(options: CliOptions): ConvexBillingState {
    if (options.convexJson) {
        return JSON.parse(readFileSync(options.convexJson, "utf8")) as ConvexBillingState;
    }

    const stdout = execFileSync(
        "npx",
        [
            "--no-install",
            "convex",
            "run",
            "billing:reconcileSnapshot",
            "{}",
            ...(options.prod ? ["--prod"] : []),
        ],
        { encoding: "utf8", stdio: ["ignore", "pipe", "inherit"], maxBuffer: 64 * 1024 * 1024 },
    );

    // `convex run` prints the JSON result, but the CLI may emit leading lines:
    // take the outermost object rather than assuming a clean stream.
    const start = stdout.indexOf("{");
    const end = stdout.lastIndexOf("}");
    if (start === -1 || end === -1 || end < start) {
        throw new Error("Unexpected `convex run` output: no JSON object found on stdout");
    }

    return JSON.parse(stdout.slice(start, end + 1)) as ConvexBillingState;
}

async function main() {
    config({ path: process.env.NUXT_ENV === "prod" ? ".env.prod" : ".env" });

    const options = parseArgs(process.argv.slice(2));
    const legacy = await readLegacyState();
    const convex = readConvexState(options);

    const report = compareBillingStates(legacy, convex);
    const output = {
        generatedAt: new Date().toISOString(),
        source: options.convexJson ? "convex-snapshot-file" : options.prod ? "convex-prod" : "convex-dev",
        configuredProducts: convex.configured,
        ...report,
    };

    if (options.out) {
        const { writeFile, mkdir } = await import("node:fs/promises");
        const { dirname, resolve } = await import("node:path");
        await mkdir(dirname(resolve(options.out)), { recursive: true });
        await writeFile(resolve(options.out), JSON.stringify(output, null, 2), "utf8");
    }

    console.log(JSON.stringify(output, null, 2));

    if (report.mismatches.length > 0) {
        console.error(
            `[reconcile-creem] ${report.mismatches.length} mismatch(es) between legacy Neon and Convex`,
        );
        process.exit(1);
    }
}

// Importable for its pure comparator (`test/migration/reconcile-creem.test.ts`)
// without executing the CLI on import.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
    main().catch((error: unknown) => {
        console.error(`[reconcile-creem] ${error instanceof Error ? error.message : String(error)}`);
        process.exit(1);
    });
}
