/**
 * Guest Repository — Drizzle queries for Ceremly guests (SPEC §6, owner B1).
 *
 * All queries are org-scoped BY-CONSTRUCTION (WHERE organizationId) and,
 * where appropriate, also event-scoped (WHERE eventId): a guestId from another
 * event/org is never returned.
 */
import { and, asc, desc, eq, isNull, sql } from "drizzle-orm";
import { getDB } from "../utils/db";
import * as schema from "../database/schema";

/** Values for inserting a guest (token generated by the service). */
export interface CreateGuestValues {
    firstName: string;
    lastName: string;
    email: string | null;
    phone: string | null;
    groupName: string | null;
    notes: string | null;
    token: string;
}

/**
 * All guests for an event (INCLUDING removed ones, flag `removedAt`) with
 * their optional response joined (LEFT JOIN, each guest has at most 1 response).
 */
export async function findGuestsByEventWithResponse(organizationId: string, eventId: string) {
    const db = getDB();
    return db
        .select({
            guest: schema.guests,
            responseId: schema.rsvpResponses.id,
            attending: schema.rsvpResponses.attending,
            companionsCount: schema.rsvpResponses.companionsCount,
            answers: schema.rsvpResponses.answers,
            declineMessage: schema.rsvpResponses.declineMessage,
            submittedAt: schema.rsvpResponses.submittedAt,
            responseUpdatedAt: schema.rsvpResponses.updatedAt,
        })
        .from(schema.guests)
        .leftJoin(schema.rsvpResponses, eq(schema.rsvpResponses.guestId, schema.guests.id))
        .where(
            and(
                eq(schema.guests.organizationId, organizationId),
                eq(schema.guests.eventId, eventId),
            ),
        )
        .orderBy(asc(schema.guests.createdAt));
}

/** Single guest fetch scoped org+event: undefined if out of scope (no leak). */
export async function findGuestByIdScoped(
    organizationId: string,
    eventId: string,
    guestId: string,
) {
    const db = getDB();
    const rows = await db
        .select()
        .from(schema.guests)
        .where(
            and(
                eq(schema.guests.id, guestId),
                eq(schema.guests.organizationId, organizationId),
                eq(schema.guests.eventId, eventId),
            ),
        )
        .limit(1);
    return rows[0];
}

/** Creates a guest. Throws 23505 on token collision (retry in the service). */
export async function createGuestRow(
    organizationId: string,
    eventId: string,
    values: CreateGuestValues,
) {
    const db = getDB();
    const rows = await db
        .insert(schema.guests)
        .values({ organizationId, eventId, ...values })
        .returning();
    return rows[0];
}

/** Bulk insert (CSV import): single statement, returning for the count.
 *  Throws 23505 on token collision (regeneration + retry in the service). */
export async function createGuestsBulk(
    organizationId: string,
    eventId: string,
    values: CreateGuestValues[],
) {
    const db = getDB();
    if (values.length === 0) return [];
    return db
        .insert(schema.guests)
        .values(values.map((v) => ({ organizationId, eventId, ...v })))
        .returning({ id: schema.guests.id });
}

/** Scoped update (the token is NEVER in the patch: immutable by contract). */
export async function updateGuestScoped(
    organizationId: string,
    eventId: string,
    guestId: string,
    patch: Partial<typeof schema.guests.$inferInsert>,
) {
    const db = getDB();
    if (Object.keys(patch).length === 0) {
        // Idempotent no-op: avoids `.set({})` (drizzle "No values to set" → 500).
        return findGuestByIdScoped(organizationId, eventId, guestId);
    }
    const rows = await db
        .update(schema.guests)
        .set(patch)
        .where(
            and(
                eq(schema.guests.id, guestId),
                eq(schema.guests.organizationId, organizationId),
                eq(schema.guests.eventId, eventId),
            ),
        )
        .returning();
    return rows[0];
}

/** Soft-delete: sets removedAt (link inactive, response preserved — PRD edge case). */
export async function softDeleteGuestScoped(
    organizationId: string,
    eventId: string,
    guestId: string,
) {
    const db = getDB();
    const rows = await db
        .update(schema.guests)
        .set({ removedAt: new Date() })
        .where(
            and(
                eq(schema.guests.id, guestId),
                eq(schema.guests.organizationId, organizationId),
                eq(schema.guests.eventId, eventId),
            ),
        )
        .returning();
    return rows[0];
}

/** Count of ACTIVE guests (not removed) for Free plan limit enforcement. */
export async function countActiveGuests(organizationId: string, eventId: string): Promise<number> {
    const db = getDB();
    const rows = await db
        .select({ count: sql<number>`count(*)::int` })
        .from(schema.guests)
        .where(
            and(
                eq(schema.guests.organizationId, organizationId),
                eq(schema.guests.eventId, eventId),
                isNull(schema.guests.removedAt),
            ),
        );
    return rows[0]?.count ?? 0;
}

/** Names of active guests (for duplicate warnings in bulk import). */
export async function findActiveGuestNames(organizationId: string, eventId: string) {
    const db = getDB();
    return db
        .select({
            firstName: schema.guests.firstName,
            lastName: schema.guests.lastName,
        })
        .from(schema.guests)
        .where(
            and(
                eq(schema.guests.organizationId, organizationId),
                eq(schema.guests.eventId, eventId),
                isNull(schema.guests.removedAt),
            ),
        );
}

/** Emails (lowercase) of active guests with an email — for bulk import deduplication. */
export async function findActiveGuestEmails(organizationId: string, eventId: string): Promise<string[]> {
    const db = getDB();
    const rows = await db
        .select({ email: schema.guests.email })
        .from(schema.guests)
        .where(
            and(
                eq(schema.guests.organizationId, organizationId),
                eq(schema.guests.eventId, eventId),
                isNull(schema.guests.removedAt),
                sql`${schema.guests.email} IS NOT NULL`,
            ),
        );
    return rows.map((r) => (r.email as string).toLowerCase());
}

/** True if an ACTIVE guest with that email (case-insensitive) already exists in the event. */
export async function activeGuestEmailExists(
    organizationId: string,
    eventId: string,
    email: string,
): Promise<boolean> {
    const db = getDB();
    const rows = await db
        .select({ id: schema.guests.id })
        .from(schema.guests)
        .where(
            and(
                eq(schema.guests.organizationId, organizationId),
                eq(schema.guests.eventId, eventId),
                isNull(schema.guests.removedAt),
                sql`lower(${schema.guests.email}) = ${email.toLowerCase()}`,
            ),
        )
        .limit(1);
    return rows.length > 0;
}

/** Latest response for a guest (at most one: guestId UNIQUE on rsvp_responses). */
export async function findResponseByGuestScoped(organizationId: string, guestId: string) {
    const db = getDB();
    const rows = await db
        .select()
        .from(schema.rsvpResponses)
        .where(
            and(
                eq(schema.rsvpResponses.guestId, guestId),
                eq(schema.rsvpResponses.organizationId, organizationId),
            ),
        )
        .limit(1);
    return rows[0];
}

/** A guest's activities, most recent first (guest detail timeline). */
export async function findActivitiesByGuestScoped(organizationId: string, guestId: string) {
    const db = getDB();
    return db
        .select()
        .from(schema.guestActivities)
        .where(
            and(
                eq(schema.guestActivities.guestId, guestId),
                eq(schema.guestActivities.organizationId, organizationId),
            ),
        )
        .orderBy(desc(schema.guestActivities.createdAt));
}
